#!/bin/sh

packer build -var "aws_access_key=${AWS_ACCESS_KEY:?Please set AWS_ACCESS_KEY}" \
    -var "aws_secret_key=${AWS_SECRET_KEY:?Please set AWS_SECRET_KEY}" \
    -var "git_user=${GIT_USER:?Please set GIT_USER}" \
    -var "git_password=${GIT_PASSWORD:?Please set GIT_PASSWORD (using a personal token)}" \
    $@
